// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/providers/recently_played_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:app/enums.dart' as _i6;
import 'package:app/models/models.dart' as _i4;
import 'package:app/providers/providers.dart' as _i3;
import 'package:app/values/values.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginationResult_0<T> extends _i1.SmartFake
    implements _i2.PaginationResult<T> {
  _FakePaginationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlayableProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayableProvider extends _i1.Mock implements _i3.PlayableProvider {
  MockPlayableProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Playable<dynamic>> get playables => (super.noSuchMethod(
        Invocation.getter(#playables),
        returnValue: <_i4.Playable<dynamic>>[],
      ) as List<_i4.Playable<dynamic>>);

  @override
  set playables(List<_i4.Playable<dynamic>>? _playables) => super.noSuchMethod(
        Invocation.setter(
          #playables,
          _playables,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i4.Playable<dynamic>> syncWithVault(dynamic _playables) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWithVault,
          [_playables],
        ),
        returnValue: <_i4.Playable<dynamic>>[],
      ) as List<_i4.Playable<dynamic>>);

  @override
  _i4.Playable<dynamic>? byId(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #byId,
        [id],
      )) as _i4.Playable<dynamic>?);

  @override
  _i5.Future<_i2.PaginationResult<_i4.Playable<dynamic>>> paginate(
          _i3.PlayablePaginationConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginate,
          [config],
        ),
        returnValue:
            _i5.Future<_i2.PaginationResult<_i4.Playable<dynamic>>>.value(
                _FakePaginationResult_0<_i4.Playable<dynamic>>(
          this,
          Invocation.method(
            #paginate,
            [config],
          ),
        )),
      ) as _i5.Future<_i2.PaginationResult<_i4.Playable<dynamic>>>);

  @override
  _i5.Future<List<_i4.Playable<dynamic>>> fetchForArtist(
    dynamic artistId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForArtist,
          [artistId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i5.Future<List<_i4.Playable<dynamic>>>.value(
            <_i4.Playable<dynamic>>[]),
      ) as _i5.Future<List<_i4.Playable<dynamic>>>);

  @override
  _i5.Future<List<_i4.Playable<dynamic>>> fetchForAlbum(
    dynamic albumId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForAlbum,
          [albumId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i5.Future<List<_i4.Playable<dynamic>>>.value(
            <_i4.Playable<dynamic>>[]),
      ) as _i5.Future<List<_i4.Playable<dynamic>>>);

  @override
  _i5.Future<List<_i4.Playable<dynamic>>> fetchForPlaylist(
    dynamic playlistId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForPlaylist,
          [playlistId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i5.Future<List<_i4.Playable<dynamic>>>.value(
            <_i4.Playable<dynamic>>[]),
      ) as _i5.Future<List<_i4.Playable<dynamic>>>);

  @override
  _i5.Future<List<_i4.Playable<dynamic>>> fetchForPodcast(
    String? podcastId, {
    bool? forceRefresh = false,
    bool? getUpdates = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForPodcast,
          [podcastId],
          {
            #forceRefresh: forceRefresh,
            #getUpdates: getUpdates,
          },
        ),
        returnValue: _i5.Future<List<_i4.Playable<dynamic>>>.value(
            <_i4.Playable<dynamic>>[]),
      ) as _i5.Future<List<_i4.Playable<dynamic>>>);

  @override
  _i5.Future<List<_i4.Playable<dynamic>>> fetchRandom({int? limit = 500}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandom,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i4.Playable<dynamic>>>.value(
            <_i4.Playable<dynamic>>[]),
      ) as _i5.Future<List<_i4.Playable<dynamic>>>);

  @override
  _i5.Future<List<_i4.Playable<dynamic>>> fetchInOrder({
    String? sortField = 'title',
    _i6.SortOrder? order = _i6.SortOrder.asc,
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchInOrder,
          [],
          {
            #sortField: sortField,
            #order: order,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i4.Playable<dynamic>>>.value(
            <_i4.Playable<dynamic>>[]),
      ) as _i5.Future<List<_i4.Playable<dynamic>>>);

  @override
  List<_i4.Playable<dynamic>> parseFromJson(dynamic json) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseFromJson,
          [json],
        ),
        returnValue: <_i4.Playable<dynamic>>[],
      ) as List<_i4.Playable<dynamic>>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i5.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
