// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/screens/album_action_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:app/enums.dart' as _i6;
import 'package:app/models/models.dart' as _i2;
import 'package:app/providers/providers.dart' as _i4;
import 'package:app/values/values.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAlbum_0 extends _i1.SmartFake implements _i2.Album {
  _FakeAlbum_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginationResult_1<T> extends _i1.SmartFake
    implements _i3.PaginationResult<T> {
  _FakePaginationResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AlbumProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlbumProvider extends _i1.Mock implements _i4.AlbumProvider {
  MockAlbumProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Album> get albums => (super.noSuchMethod(
        Invocation.getter(#albums),
        returnValue: <_i2.Album>[],
      ) as List<_i2.Album>);

  @override
  String get sortField => (super.noSuchMethod(
        Invocation.getter(#sortField),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#sortField),
        ),
      ) as String);

  @override
  _i6.SortOrder get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i6.SortOrder.asc,
      ) as _i6.SortOrder);

  @override
  set albums(List<_i2.Album>? _albums) => super.noSuchMethod(
        Invocation.setter(
          #albums,
          _albums,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sortField(String? field) => super.noSuchMethod(
        Invocation.setter(
          #sortField,
          field,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sortOrder(_i6.SortOrder? order) => super.noSuchMethod(
        Invocation.setter(
          #sortOrder,
          order,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.Album> byIds(List<dynamic>? ids) => (super.noSuchMethod(
        Invocation.method(
          #byIds,
          [ids],
        ),
        returnValue: <_i2.Album>[],
      ) as List<_i2.Album>);

  @override
  _i7.Future<_i2.Album> resolve(
    dynamic id, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolve,
          [id],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i7.Future<_i2.Album>.value(_FakeAlbum_0(
          this,
          Invocation.method(
            #resolve,
            [id],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i7.Future<_i2.Album>);

  @override
  List<_i2.Album> syncWithVault(dynamic _albums) => (super.noSuchMethod(
        Invocation.method(
          #syncWithVault,
          [_albums],
        ),
        returnValue: <_i2.Album>[],
      ) as List<_i2.Album>);

  @override
  _i7.Future<void> paginate() => (super.noSuchMethod(
        Invocation.method(
          #paginate,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> toggleFavorite(_i2.Album? album) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [album],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> update(
    _i2.Album? album, {
    required String? name,
    int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [album],
          {
            #name: name,
            #year: year,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i7.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PlayableProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayableProvider extends _i1.Mock implements _i4.PlayableProvider {
  MockPlayableProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Playable<dynamic>> get playables => (super.noSuchMethod(
        Invocation.getter(#playables),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  set playables(List<_i2.Playable<dynamic>>? _playables) => super.noSuchMethod(
        Invocation.setter(
          #playables,
          _playables,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.Playable<dynamic>> syncWithVault(dynamic _playables) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWithVault,
          [_playables],
        ),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  _i2.Playable<dynamic>? byId(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #byId,
        [id],
      )) as _i2.Playable<dynamic>?);

  @override
  _i7.Future<_i3.PaginationResult<_i2.Playable<dynamic>>> paginate(
          _i4.PlayablePaginationConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginate,
          [config],
        ),
        returnValue:
            _i7.Future<_i3.PaginationResult<_i2.Playable<dynamic>>>.value(
                _FakePaginationResult_1<_i2.Playable<dynamic>>(
          this,
          Invocation.method(
            #paginate,
            [config],
          ),
        )),
      ) as _i7.Future<_i3.PaginationResult<_i2.Playable<dynamic>>>);

  @override
  _i7.Future<List<_i2.Playable<dynamic>>> fetchForArtist(
    dynamic artistId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForArtist,
          [artistId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i7.Future<List<_i2.Playable<dynamic>>>.value(
            <_i2.Playable<dynamic>>[]),
      ) as _i7.Future<List<_i2.Playable<dynamic>>>);

  @override
  _i7.Future<_i3.PaginationResult<_i2.Playable<dynamic>>> paginateByGenre(
    String? genreId, {
    int? page = 1,
    String? sort = 'title',
    _i6.SortOrder? order = _i6.SortOrder.asc,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #paginateByGenre,
          [genreId],
          {
            #page: page,
            #sort: sort,
            #order: order,
          },
        ),
        returnValue:
            _i7.Future<_i3.PaginationResult<_i2.Playable<dynamic>>>.value(
                _FakePaginationResult_1<_i2.Playable<dynamic>>(
          this,
          Invocation.method(
            #paginateByGenre,
            [genreId],
            {
              #page: page,
              #sort: sort,
              #order: order,
            },
          ),
        )),
      ) as _i7.Future<_i3.PaginationResult<_i2.Playable<dynamic>>>);

  @override
  _i7.Future<List<_i2.Playable<dynamic>>> fetchForAlbum(
    dynamic albumId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForAlbum,
          [albumId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i7.Future<List<_i2.Playable<dynamic>>>.value(
            <_i2.Playable<dynamic>>[]),
      ) as _i7.Future<List<_i2.Playable<dynamic>>>);

  @override
  _i7.Future<List<_i2.Playable<dynamic>>> fetchForPlaylist(
    dynamic playlistId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForPlaylist,
          [playlistId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i7.Future<List<_i2.Playable<dynamic>>>.value(
            <_i2.Playable<dynamic>>[]),
      ) as _i7.Future<List<_i2.Playable<dynamic>>>);

  @override
  _i7.Future<List<_i2.Playable<dynamic>>> fetchForPodcast(
    String? podcastId, {
    bool? forceRefresh = false,
    bool? getUpdates = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForPodcast,
          [podcastId],
          {
            #forceRefresh: forceRefresh,
            #getUpdates: getUpdates,
          },
        ),
        returnValue: _i7.Future<List<_i2.Playable<dynamic>>>.value(
            <_i2.Playable<dynamic>>[]),
      ) as _i7.Future<List<_i2.Playable<dynamic>>>);

  @override
  _i7.Future<List<_i2.Playable<dynamic>>> fetchRandom({int? limit = 500}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandom,
          [],
          {#limit: limit},
        ),
        returnValue: _i7.Future<List<_i2.Playable<dynamic>>>.value(
            <_i2.Playable<dynamic>>[]),
      ) as _i7.Future<List<_i2.Playable<dynamic>>>);

  @override
  _i7.Future<List<_i2.Playable<dynamic>>> fetchInOrder({
    String? sortField = 'title',
    _i6.SortOrder? order = _i6.SortOrder.asc,
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchInOrder,
          [],
          {
            #sortField: sortField,
            #order: order,
            #limit: limit,
          },
        ),
        returnValue: _i7.Future<List<_i2.Playable<dynamic>>>.value(
            <_i2.Playable<dynamic>>[]),
      ) as _i7.Future<List<_i2.Playable<dynamic>>>);

  @override
  List<_i2.Playable<dynamic>> parseFromJson(dynamic json) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseFromJson,
          [json],
        ),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i7.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
