// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/screens/create_playlist_folder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:app/models/models.dart' as _i2;
import 'package:app/providers/playlist_folder_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlaylistFolder_0 extends _i1.SmartFake
    implements _i2.PlaylistFolder {
  _FakePlaylistFolder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlaylistFolderProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistFolderProvider extends _i1.Mock
    implements _i3.PlaylistFolderProvider {
  MockPlaylistFolderProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.PlaylistFolder> get folders => (super.noSuchMethod(
        Invocation.getter(#folders),
        returnValue: <_i2.PlaylistFolder>[],
      ) as List<_i2.PlaylistFolder>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void init(List<dynamic>? folderData) => super.noSuchMethod(
        Invocation.method(
          #init,
          [folderData],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.PlaylistFolder? byId(String? id) => (super.noSuchMethod(Invocation.method(
        #byId,
        [id],
      )) as _i2.PlaylistFolder?);

  @override
  _i4.Future<_i2.PlaylistFolder> create({required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {#name: name},
        ),
        returnValue: _i4.Future<_i2.PlaylistFolder>.value(_FakePlaylistFolder_0(
          this,
          Invocation.method(
            #create,
            [],
            {#name: name},
          ),
        )),
      ) as _i4.Future<_i2.PlaylistFolder>);

  @override
  _i4.Future<void> rename(
    _i2.PlaylistFolder? folder, {
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rename,
          [folder],
          {#name: name},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> remove(_i2.PlaylistFolder? folder) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [folder],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
