// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/screens/data_loading_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:app/models/models.dart' as _i2;
import 'package:app/providers/providers.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataProvider extends _i1.Mock implements _i3.DataProvider {
  MockDataProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DownloadProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadProvider extends _i1.Mock implements _i3.DownloadProvider {
  MockDownloadProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Playable<dynamic>> get playables => (super.noSuchMethod(
        Invocation.getter(#playables),
        returnValue: <_i2.Playable<dynamic>>[],
      ) as List<_i2.Playable<dynamic>>);

  @override
  _i4.Stream<bool> get downloadsClearedStream => (super.noSuchMethod(
        Invocation.getter(#downloadsClearedStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Stream<_i2.Playable<dynamic>> get downloadRemovedStream =>
      (super.noSuchMethod(
        Invocation.getter(#downloadRemovedStream),
        returnValue: _i4.Stream<_i2.Playable<dynamic>>.empty(),
      ) as _i4.Stream<_i2.Playable<dynamic>>);

  @override
  _i4.Stream<_i3.Download> get playableDownloadedStream => (super.noSuchMethod(
        Invocation.getter(#playableDownloadedStream),
        returnValue: _i4.Stream<_i3.Download>.empty(),
      ) as _i4.Stream<_i3.Download>);

  @override
  _i4.Future<String> get downloadsDir => (super.noSuchMethod(
        Invocation.getter(#downloadsDir),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.getter(#downloadsDir),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> download({required _i2.Playable<dynamic>? playable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [],
          {#playable: playable},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i3.Download? getForPlayable(_i2.Playable<dynamic>? playable) =>
      (super.noSuchMethod(Invocation.method(
        #getForPlayable,
        [playable],
      )) as _i3.Download?);

  @override
  bool has({required _i2.Playable<dynamic>? playable}) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [],
          {#playable: playable},
        ),
        returnValue: false,
      ) as bool);

  @override
  void persistMetadata() => super.noSuchMethod(
        Invocation.method(
          #persistMetadata,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void persistMetadataIfNeeded(_i2.Playable<dynamic>? playable) =>
      super.noSuchMethod(
        Invocation.method(
          #persistMetadataIfNeeded,
          [playable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> removeForPlayable(_i2.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeForPlayable,
          [playable],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i3.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.User get authUser => (super.noSuchMethod(
        Invocation.getter(#authUser),
        returnValue: _FakeUser_0(
          this,
          Invocation.getter(#authUser),
        ),
      ) as _i2.User);

  @override
  _i4.Future<_i3.TwoFactorChallenge?> login({
    required String? host,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #host: host,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i3.TwoFactorChallenge?>.value(),
      ) as _i4.Future<_i3.TwoFactorChallenge?>);

  @override
  _i4.Future<void> completeTwoFactorChallenge({
    required String? loginToken,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTwoFactorChallenge,
          [],
          {
            #loginToken: loginToken,
            #code: code,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loginWithOneTimeToken({
    required String? host,
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithOneTimeToken,
          [],
          {
            #host: host,
            #token: token,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setAuthUser(_i2.User? user) => super.noSuchMethod(
        Invocation.method(
          #setAuthUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.User?> tryGetAuthUser() => (super.noSuchMethod(
        Invocation.method(
          #tryGetAuthUser,
          [],
        ),
        returnValue: _i4.Future<_i2.User?>.value(),
      ) as _i4.Future<_i2.User?>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
