// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/screens/genres_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:app/enums.dart' as _i5;
import 'package:app/models/models.dart' as _i3;
import 'package:app/providers/providers.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GenreProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenreProvider extends _i1.Mock implements _i2.GenreProvider {
  MockGenreProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Genre> get genres => (super.noSuchMethod(
        Invocation.getter(#genres),
        returnValue: <_i3.Genre>[],
      ) as List<_i3.Genre>);

  @override
  String get sortField => (super.noSuchMethod(
        Invocation.getter(#sortField),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#sortField),
        ),
      ) as String);

  @override
  _i5.SortOrder get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i5.SortOrder.asc,
      ) as _i5.SortOrder);

  @override
  set genres(List<_i3.Genre>? _genres) => super.noSuchMethod(
        Invocation.setter(
          #genres,
          _genres,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sortField(String? field) => super.noSuchMethod(
        Invocation.setter(
          #sortField,
          field,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sortOrder(_i5.SortOrder? order) => super.noSuchMethod(
        Invocation.setter(
          #sortOrder,
          order,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Genre? byId(String? id) => (super.noSuchMethod(Invocation.method(
        #byId,
        [id],
      )) as _i3.Genre?);

  @override
  _i6.Future<void> fetch() => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i6.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
