// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/screens/radio_station_action_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:app/models/models.dart' as _i2;
import 'package:app/providers/radio_player_provider.dart' as _i6;
import 'package:app/providers/radio_station_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRadioStation_0 extends _i1.SmartFake implements _i2.RadioStation {
  _FakeRadioStation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RadioStationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRadioStationProvider extends _i1.Mock
    implements _i3.RadioStationProvider {
  MockRadioStationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.RadioStation> get stations => (super.noSuchMethod(
        Invocation.getter(#stations),
        returnValue: <_i2.RadioStation>[],
      ) as List<_i2.RadioStation>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.RadioStation> create({
    required String? name,
    required String? url,
    String? description,
    bool? isPublic = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #name: name,
            #url: url,
            #description: description,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i4.Future<_i2.RadioStation>.value(_FakeRadioStation_0(
          this,
          Invocation.method(
            #create,
            [],
            {
              #name: name,
              #url: url,
              #description: description,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i4.Future<_i2.RadioStation>);

  @override
  _i4.Future<void> update(
    _i2.RadioStation? station, {
    required String? name,
    required String? url,
    String? description,
    bool? isPublic = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [station],
          {
            #name: name,
            #url: url,
            #description: description,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> remove(_i2.RadioStation? station) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [station],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleFavorite(_i2.RadioStation? station) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [station],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getNowPlaying(_i2.RadioStation? station) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlaying,
          [station],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RadioPlayerProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRadioPlayerProvider extends _i1.Mock
    implements _i6.RadioPlayerProvider {
  MockRadioPlayerProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get playing => (super.noSuchMethod(
        Invocation.getter(#playing),
        returnValue: false,
      ) as bool);

  @override
  bool get loading => (super.noSuchMethod(
        Invocation.getter(#loading),
        returnValue: false,
      ) as bool);

  @override
  bool get active => (super.noSuchMethod(
        Invocation.getter(#active),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> play(_i2.RadioStation? station) => (super.noSuchMethod(
        Invocation.method(
          #play,
          [station],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> togglePlayPause() => (super.noSuchMethod(
        Invocation.method(
          #togglePlayPause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void refreshMediaItem() => super.noSuchMethod(
        Invocation.method(
          #refreshMediaItem,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
