// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/widgets/album_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i9;

import 'package:app/enums.dart' as _i8;
import 'package:app/models/models.dart' as _i2;
import 'package:app/providers/album_provider.dart' as _i6;
import 'package:app/router.dart' as _i3;
import 'package:flutter/cupertino.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAlbum_0 extends _i1.SmartFake implements _i2.Album {
  _FakeAlbum_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRouter extends _i1.Mock implements _i3.AppRouter {
  MockAppRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> gotoAlbumDetailsScreen(
    _i5.BuildContext? context, {
    required dynamic albumId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #gotoAlbumDetailsScreen,
          [context],
          {#albumId: albumId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> gotoArtistDetailsScreen(
    _i5.BuildContext? context, {
    required dynamic artistId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #gotoArtistDetailsScreen,
          [context],
          {#artistId: artistId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  dynamic gotoPodcastDetailsScreen(
    _i5.BuildContext? context, {
    required String? podcastId,
  }) =>
      super.noSuchMethod(Invocation.method(
        #gotoPodcastDetailsScreen,
        [context],
        {#podcastId: podcastId},
      ));

  @override
  dynamic gotoGenreDetailsScreen(
    _i5.BuildContext? context, {
    required _i2.Genre? genre,
  }) =>
      super.noSuchMethod(Invocation.method(
        #gotoGenreDetailsScreen,
        [context],
        {#genre: genre},
      ));

  @override
  _i4.Future<void> openNowPlayingScreen(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #openNowPlayingScreen,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showCreatePlaylistSheet(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCreatePlaylistSheet,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showCreatePlaylistFolderSheet(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCreatePlaylistFolderSheet,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showPlayableActionSheet(
    _i5.BuildContext? context, {
    required _i2.Playable<dynamic>? playable,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showPlayableActionSheet,
          [context],
          {#playable: playable},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showAddPodcastSheet(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAddPodcastSheet,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AlbumProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlbumProvider extends _i1.Mock implements _i6.AlbumProvider {
  MockAlbumProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Album> get albums => (super.noSuchMethod(
        Invocation.getter(#albums),
        returnValue: <_i2.Album>[],
      ) as List<_i2.Album>);

  @override
  String get sortField => (super.noSuchMethod(
        Invocation.getter(#sortField),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#sortField),
        ),
      ) as String);

  @override
  _i8.SortOrder get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i8.SortOrder.asc,
      ) as _i8.SortOrder);

  @override
  set albums(List<_i2.Album>? _albums) => super.noSuchMethod(
        Invocation.setter(
          #albums,
          _albums,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sortField(String? field) => super.noSuchMethod(
        Invocation.setter(
          #sortField,
          field,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sortOrder(_i8.SortOrder? order) => super.noSuchMethod(
        Invocation.setter(
          #sortOrder,
          order,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.Album> byIds(List<dynamic>? ids) => (super.noSuchMethod(
        Invocation.method(
          #byIds,
          [ids],
        ),
        returnValue: <_i2.Album>[],
      ) as List<_i2.Album>);

  @override
  _i4.Future<_i2.Album> resolve(
    dynamic id, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolve,
          [id],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<_i2.Album>.value(_FakeAlbum_0(
          this,
          Invocation.method(
            #resolve,
            [id],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i4.Future<_i2.Album>);

  @override
  List<_i2.Album> syncWithVault(dynamic _albums) => (super.noSuchMethod(
        Invocation.method(
          #syncWithVault,
          [_albums],
        ),
        returnValue: <_i2.Album>[],
      ) as List<_i2.Album>);

  @override
  _i4.Future<void> paginate() => (super.noSuchMethod(
        Invocation.method(
          #paginate,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> update(
    _i2.Album? album, {
    required String? name,
    int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [album],
          {
            #name: name,
            #year: year,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
