// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/widgets/artist_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/models/models.dart' as _i5;
import 'package:app/router.dart' as _i2;
import 'package:flutter/cupertino.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRouter extends _i1.Mock implements _i2.AppRouter {
  MockAppRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> gotoAlbumDetailsScreen(
    _i4.BuildContext? context, {
    required dynamic albumId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #gotoAlbumDetailsScreen,
          [context],
          {#albumId: albumId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> gotoArtistDetailsScreen(
    _i4.BuildContext? context, {
    required dynamic artistId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #gotoArtistDetailsScreen,
          [context],
          {#artistId: artistId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  dynamic gotoPodcastDetailsScreen(
    _i4.BuildContext? context, {
    required String? podcastId,
  }) =>
      super.noSuchMethod(Invocation.method(
        #gotoPodcastDetailsScreen,
        [context],
        {#podcastId: podcastId},
      ));

  @override
  _i3.Future<void> openNowPlayingScreen(_i4.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #openNowPlayingScreen,
          [context],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showCreatePlaylistSheet(_i4.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCreatePlaylistSheet,
          [context],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showCreatePlaylistFolderSheet(_i4.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCreatePlaylistFolderSheet,
          [context],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showPlayableActionSheet(
    _i4.BuildContext? context, {
    required _i5.Playable<dynamic>? playable,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showPlayableActionSheet,
          [context],
          {#playable: playable},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showAddPodcastSheet(_i4.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAddPodcastSheet,
          [context],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
