// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/widgets/oops_box_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/models/models.dart' as _i2;
import 'package:app/providers/auth_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i3.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.User get authUser => (super.noSuchMethod(
        Invocation.getter(#authUser),
        returnValue: _FakeUser_0(
          this,
          Invocation.getter(#authUser),
        ),
      ) as _i2.User);

  @override
  _i4.Future<void> login({
    required String? host,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #host: host,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loginWithOneTimeToken({
    required String? host,
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithOneTimeToken,
          [],
          {
            #host: host,
            #token: token,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setAuthUser(_i2.User? user) => super.noSuchMethod(
        Invocation.method(
          #setAuthUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.User?> tryGetAuthUser() => (super.noSuchMethod(
        Invocation.method(
          #tryGetAuthUser,
          [],
        ),
        returnValue: _i4.Future<_i2.User?>.value(),
      ) as _i4.Future<_i2.User?>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
