// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/widgets/playlist_row_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:app/models/models.dart' as _i2;
import 'package:app/providers/playlist_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlaylist_0 extends _i1.SmartFake implements _i2.Playlist {
  _FakePlaylist_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlaylistProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistProvider extends _i1.Mock implements _i3.PlaylistProvider {
  MockPlaylistProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Playlist> get playlists => (super.noSuchMethod(
        Invocation.getter(#playlists),
        returnValue: <_i2.Playlist>[],
      ) as List<_i2.Playlist>);

  @override
  List<_i2.Playlist> get standardPlaylists => (super.noSuchMethod(
        Invocation.getter(#standardPlaylists),
        returnValue: <_i2.Playlist>[],
      ) as List<_i2.Playlist>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> init(List<dynamic>? playlistData) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [playlistData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addToPlaylist(
    _i2.Playable<dynamic>? playable, {
    required _i2.Playlist? playlist,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToPlaylist,
          [playable],
          {#playlist: playlist},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromPlaylist(
    _i2.Playable<dynamic>? playable, {
    required _i2.Playlist? playlist,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromPlaylist,
          [playable],
          {#playlist: playlist},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Playlist> create({required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {#name: name},
        ),
        returnValue: _i4.Future<_i2.Playlist>.value(_FakePlaylist_0(
          this,
          Invocation.method(
            #create,
            [],
            {#name: name},
          ),
        )),
      ) as _i4.Future<_i2.Playlist>);

  @override
  _i4.Future<void> remove(_i2.Playlist? playlist) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [playlist],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
