// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/widgets/podcast_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:app/models/models.dart' as _i2;
import 'package:app/providers/providers.dart' as _i6;
import 'package:app/router.dart' as _i3;
import 'package:flutter/cupertino.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePodcast_0 extends _i1.SmartFake implements _i2.Podcast {
  _FakePodcast_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRouter extends _i1.Mock implements _i3.AppRouter {
  MockAppRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> gotoAlbumDetailsScreen(
    _i5.BuildContext? context, {
    required dynamic albumId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #gotoAlbumDetailsScreen,
          [context],
          {#albumId: albumId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> gotoArtistDetailsScreen(
    _i5.BuildContext? context, {
    required dynamic artistId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #gotoArtistDetailsScreen,
          [context],
          {#artistId: artistId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  dynamic gotoPodcastDetailsScreen(
    _i5.BuildContext? context, {
    required String? podcastId,
  }) =>
      super.noSuchMethod(Invocation.method(
        #gotoPodcastDetailsScreen,
        [context],
        {#podcastId: podcastId},
      ));

  @override
  dynamic gotoGenreDetailsScreen(
    _i5.BuildContext? context, {
    required _i2.Genre? genre,
  }) =>
      super.noSuchMethod(Invocation.method(
        #gotoGenreDetailsScreen,
        [context],
        {#genre: genre},
      ));

  @override
  _i4.Future<void> openNowPlayingScreen(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #openNowPlayingScreen,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showCreatePlaylistSheet(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCreatePlaylistSheet,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showCreatePlaylistFolderSheet(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCreatePlaylistFolderSheet,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showPlayableActionSheet(
    _i5.BuildContext? context, {
    required _i2.Playable<dynamic>? playable,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showPlayableActionSheet,
          [context],
          {#playable: playable},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showAddPodcastSheet(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAddPodcastSheet,
          [context],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PodcastProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPodcastProvider extends _i1.Mock implements _i6.PodcastProvider {
  MockPodcastProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Podcast> get podcasts => (super.noSuchMethod(
        Invocation.getter(#podcasts),
        returnValue: <_i2.Podcast>[],
      ) as List<_i2.Podcast>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unsubscribePodcast(_i2.Podcast? podcast) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsubscribePodcast,
          [podcast],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Podcast> add({required String? url}) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [],
          {#url: url},
        ),
        returnValue: _i4.Future<_i2.Podcast>.value(_FakePodcast_0(
          this,
          Invocation.method(
            #add,
            [],
            {#url: url},
          ),
        )),
      ) as _i4.Future<_i2.Podcast>);

  @override
  _i4.Future<_i2.Podcast> resolve(
    String? id, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolve,
          [id],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<_i2.Podcast>.value(_FakePodcast_0(
          this,
          Invocation.method(
            #resolve,
            [id],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i4.Future<_i2.Podcast>);

  @override
  _i4.Future<num> getEpisodeProgress(_i2.Episode? episode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodeProgress,
          [episode],
        ),
        returnValue: _i4.Future<num>.value(0),
      ) as _i4.Future<num>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
