// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/ui/widgets/song_cache_icon_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/models/models.dart' as _i3;
import 'package:app/providers/providers.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DownloadProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadProvider extends _i1.Mock implements _i2.DownloadProvider {
  MockDownloadProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Playable<dynamic>> get playables => (super.noSuchMethod(
        Invocation.getter(#playables),
        returnValue: <_i3.Playable<dynamic>>[],
      ) as List<_i3.Playable<dynamic>>);

  @override
  _i4.Stream<bool> get downloadsClearedStream => (super.noSuchMethod(
        Invocation.getter(#downloadsClearedStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Stream<_i3.Playable<dynamic>> get downloadRemovedStream =>
      (super.noSuchMethod(
        Invocation.getter(#downloadRemovedStream),
        returnValue: _i4.Stream<_i3.Playable<dynamic>>.empty(),
      ) as _i4.Stream<_i3.Playable<dynamic>>);

  @override
  _i4.Stream<_i2.Download> get playableDownloadedStream => (super.noSuchMethod(
        Invocation.getter(#playableDownloadedStream),
        returnValue: _i4.Stream<_i2.Download>.empty(),
      ) as _i4.Stream<_i2.Download>);

  @override
  _i4.Future<String> get downloadsDir => (super.noSuchMethod(
        Invocation.getter(#downloadsDir),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.getter(#downloadsDir),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> download({required _i3.Playable<dynamic>? playable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [],
          {#playable: playable},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Download? getForPlayable(_i3.Playable<dynamic>? playable) =>
      (super.noSuchMethod(Invocation.method(
        #getForPlayable,
        [playable],
      )) as _i2.Download?);

  @override
  bool has({required _i3.Playable<dynamic>? playable}) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [],
          {#playable: playable},
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> removeForPlayable(_i3.Playable<dynamic>? playable) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeForPlayable,
          [playable],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void unsubscribeAll() => super.noSuchMethod(
        Invocation.method(
          #unsubscribeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribe(_i4.StreamSubscription<dynamic>? sub) => super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [sub],
        ),
        returnValueForMissingStub: null,
      );
}
