name: Unit Tests
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
